.TH ELEMINES 1 "10 Feb 2013" "elemines 0.2.2"

.SH NAME
elemines \- a minesweeper clone based on the EFL

.SH SYNOPSIS
.B elemines
[-h] [-f] [-m MINES] [-t THEME] [-v]

.SH DESCRIPTION

Elemines is a single-player video game. The object of the game is to clear
an abstract minefield without detonating a mine. The game is played by revealing
squares of the grid, by clicking them with a mouse. If a square containing a mine
is revealed, you lose the game. Otherwise, a digit is revealed in the square,
indicating the number of adjacent squares that contain mines.

With no option, the program starts with a 10x10 grid and 12 mines to find.


.SH CONTROLS

.TP
.I Left Mouse Button
Reveal a square.

.TP
.I Right Mouse Button
Add (or remove) a flag.

.TP
.I Middle Mouse Button
Clear around a revealed square once the correct number of mines have been flagged around it.

.SH OPTIONS

.TP
.I -h
Print list of options with short description and exit.

.TP
.I -f
Run fullscreen. This is useful on mobile devices.

.TP
.I -m MINES
Specify the number of mines hidden in the field. MINES must be an integer smaller
than the number of cells (100).

.TP
.I -t THEME
Use THEME.edj as theme file. Theme files must be in the $(datarootdir)/elemines/themes/
folder.

.TP
.I -v
Print version and license informations and exit.


.SH BUGS

Reports are welcome.


.SH HOMEPAGE

http://elemines.sourceforge.net 


.SH AUTHOR

Jerome Pinot <ngc891@gmail.com>
